language: python
python:
    - 3.5

before_install:
    # Install Anaconda
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    - bash Miniconda-latest-Linux-x86_64.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes true --set changeps1 false
    - conda update -q conda
    - conda info -a
    - conda create -q -n skeletor python=3.5
    - source activate skeletor
    - conda install -q mpi4py scipy pytest Cython sympy

    # Install mpiFFT4py
    - pip install git+https://github.com/tberlok/mpiFFT4py.git

    # Install python-mpi-bcast
    - git clone https://github.com/rainwoodman/python-mpi-bcast.git
    - (cd python-mpi-bcast && make)

    # Create tarball of Anaconda environment
    - bash python-mpi-bcast/tar-anaconda.sh anaconda.tar.gz $HOME/miniconda/envs/skeletor

    # This resets Python prefix and defines the shell function bcast()
    - source python-mpi-bcast/activate.sh /tmp/skeletor "mpiexec -n 4"

    # Broadcast the Anaconda packages as well as the code itself
    - bcast -v anaconda.tar.gz
    - git archive --format=tar.gz --prefix=skeletor/ HEAD > skeletor.tar.gz
    - bcast -v skeletor.tar.gz
    # Give highest prority to executables in scratch dir
    - export PATH="/tmp/skeletor/bin:$PATH"

install:
    - CC=mpicc LDFLAGS="-L/tmp/skeletor/lib -Wl,-rpath,/tmp/skeletor/lib -lmpich -lopa -lmpl -lrt -lpthread" python setup.py install

script:
    - mpiexec -n 4 py.test /tmp/skeletor/skeletor/tests/
