language: python
python:
    - 3.5

install:
    # Install Anaconda
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    - bash Miniconda-latest-Linux-x86_64.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes true --set changeps1 false
    - conda update -q conda
    - conda info -a
    - conda create -q -n skeletor python=3.5
    - source activate skeletor
    - conda install -q mpi4py scipy pytest Cython

    # Install mpiFFT4py
    - pip install git+https://github.com/spectralDNS/mpiFFT4py.git
    - CC=mpicc LDFLAGS="-lmpich -lopa -lmpl -lrt -lpthread" python setup.py install

script:
    - mpiexec -n 4 py.test tests/
